services:
  - type: web
    name: techstore-backend
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    startCommand: |
      php artisan migrate --force &&
      php artisan serve --host=0.0.0.0 --port=8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: techstore-db
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        fromDatabase:
          name: techstore-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: techstore-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: techstore-db
          property: password

databases:
  - name: techstore-db
    region: oregon
    plan: free
    mysqlVersion: 8
